name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip wget unzip openjdk-17-jdk
          pip install --upgrade pip setuptools wheel
          pip install kivy kivymd buildozer cython 

      - name: Install Android SDK & Command-Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest

      - name: Set Android SDK Environment Variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Android Licenses
        run: |
          source $GITHUB_ENV
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Install Required Android SDK Components (Including AIDL)
        run: |
          source $GITHUB_ENV
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest" "extras;android;m2repository" "platforms;android-30"

      - name: Verify AIDL Installation
        run: |
          source $GITHUB_ENV
          which aidl || echo "AIDL not found"

      - name: Initialize Buildozer
        run: |
          source $GITHUB_ENV
          buildozer init

      - name: Build APK
        run: |
          source $GITHUB_ENV
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pokedex-APK
          path: bin/*.apk
