name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --upgrade buildozer python-for-android cython requests

      # Step 3: Initialize Buildozer
      - name: Initialize Buildozer
        run: |
          buildozer init || { echo "Buildozer initialization failed"; exit 1; }

      # Step 4: Configure Buildozer Spec
      - name: Configure Buildozer Spec
        run: |
          echo "[app]" > buildozer.spec
          echo "title = Pokedex" >> buildozer.spec
          echo "package.name = pokedex" >> buildozer.spec
          echo "package.domain = org.example" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "version = ${{ github.ref_name }}" >> buildozer.spec
          echo "requirements = kivy, kivymd, requests" >> buildozer.spec
          echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
          echo "android.accept_sdk_license = True" >> buildozer.spec
          echo "android.skip_update = False" >> buildozer.spec
          echo "android.ndk_version = 25b" >> buildozer.spec
          echo "android.api = 31" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
          echo "android.archs = armeabi-v7a" >> buildozer.spec
          echo "android.permissions = INTERNET" >> buildozer.spec

      # Step 5: Clean Buildozer Cache
      - name: Clean Buildozer Cache
        run: |
          buildozer clean

      # Step 6: Build APK
      - name: Build APK
        run: |
          buildozer -v android debug --log_level=2 || { echo "APK build failed"; exit 1; }

      # Step 7: Verify APK Exists
      - name: Verify APK Exists
        run: |
          ls bin/*.apk || { echo "APK not found"; exit 1; }

      # Step 8: Upload APK Artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pokedex-APK
          path: bin/*.apk