name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libstdc++6 python3-pip git zip wget unzip openjdk-17-jdk

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install kivy kivymd buildozer cython

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Accept Android Licenses
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Install Android SDK Components
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest" "extras;android;m2repository"

      - name: Verify AIDL Installation
        run: |
          export PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          which aidl || { echo "AIDL not found"; exit 1; }

      - name: Initialize Buildozer
        run: |
          buildozer init

      - name: Configure Buildozer Spec
        run: |
          echo "[app]" > buildozer.spec
          echo "title = Pokedex" >> buildozer.spec
          echo "package.name = pokedex" >> buildozer.spec
          echo "package.domain = org.example" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec  # Add source directory
          echo "version = 1.0.0" >> buildozer.spec  # Add version
          echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
          echo "android.accept_sdk_license = True" >> buildozer.spec
          echo "android.skip_update = False" >> buildozer.spec
          echo "android.sdk = 34" >> buildozer.spec
          echo "android.ndk = 25b" >> buildozer.spec
          echo "android.arch = armeabi-v7a" >> buildozer.spec
          echo "android.permissions = INTERNET" >> buildozer.spec

      - name: Verify Buildozer Spec
        run: |
          cat buildozer.spec

      - name: Build APK
        run: |
          export PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pokedex-APK
          path: bin/*.apk